/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113005-g419145c11b-20231217"
#endif /* AVUTIL_FFVERSION_H */
